TRUNCATE TABLE #COHORT_DDD_XREF;
DROP TABLE #COHORT_DDD_XREF;

TRUNCATE TABLE #UNIT_CONCEPTS;
DROP TABLE #UNIT_CONCEPTS;

TRUNCATE TABLE #DOSE_FORM_GROUP;
DROP TABLE #DOSE_FORM_GROUP;

TRUNCATE TABLE #DFG_PRIORITIZED;
DROP TABLE #DFG_PRIORITIZED;