TRUNCATE TABLE #ach_analysis_116;
DROP TABLE #ach_analysis_116;

TRUNCATE TABLE #COHORT_W_FRML;
DROP TABLE #COHORT_W_FRML;

TRUNCATE TABLE #DRUG_EXPOSURES;
DROP TABLE #DRUG_EXPOSURES;

TRUNCATE TABLE #NUMERATOR_PREV;
DROP TABLE #NUMERATOR_PREV;

TRUNCATE TABLE #NUMERATOR_INC;
DROP TABLE #NUMERATOR_INC;

TRUNCATE TABLE #CALENDAR_YEARS;
DROP TABLE #CALENDAR_YEARS;